CREATE TABLE availabilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "from" DATE NOT NULL,
    "to" DATE NOT NULL,
    "placeId" INTEGER NOT NULL,
    "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("placeId") REFERENCES places(id) ON DELETE CASCADE
);